audit_header: false
title: Vero Beach Real Estate Video Blog with Kathleen Provancher
description: >-
  Our mission at Provancher Team is to be your best resource for Vero Beach real
  estate advice. Whether you are a buyer, seller, or investor, our team of
  professionals can answer any questions you might have about real estate. If
  you are looking to buy or sell a home, you can get all the information and the
  latest updates, tips, and tricks from The Provancher Team, your professional
  Vero Beach Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:
client:
  name: Kathleen Provancher
  title: Realtor®
  license_number:
  about_markdown: >-
    After graduating from Binghamton University with a degree in Psychology, I
    went on to earn my Professional Pilot Certifications through Jacksonville
    University. My husband and I have been avid real estate investors since
    1998. Formerly with another brokerage, I was a part of their \#1 real estate
    team. I then went on to join Dale Sorensen Real Estate, where I continue to
    bring my clients the best possible service and marketing. I am active in
    numerous children’s charities, as well. My husband Todd, a pilot with
    Southwest Airlines, and I reside on the barrier island with our two
    children.
  brand: Team Provancher
  brokerage: ONE Sotheby's International Realty
  market: Vero Beach
  address: 1006 Beachland Blvd.
  address_type:
  address2: 'Vero Beach, Florida, 32963 '
  address2_type:
  phone: 772-538-9700
  phone_type: Cell
  phone2: 772-208-3578
  phone2_type: Office
  email: kathleen@teamprovancher.com
  url: BuyAndSellVero.com
CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://www.buyandsellvero.com/home-valuation/
  second_CTA_text: Home Search
  second_CTA_URL: https://www.buyandsellvero.com/results-gallery/?userID=all
sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: What’s Your Vero Beach Home Worth?
    CTA_text: >-
      Are you thinking of selling your home or interested in learning about home
      prices in your neighborhood? We can help you.
    CTA_link_text: Free Home Value Report
    CTA_url: https://www.buyandsellvero.com/home-valuation/
second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: Looking for a Vero Beach Home?
    CTA_text2: Search the entire MLS for your Vero Beach home.
    CTA_link_text2: Search the MLS
    CTA_url2: https://www.buyandsellvero.com/results-gallery/?userID=all
lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:
socials:
  review_sm_icons: false
  facebook_url:
  linkedin_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:
podcast:
  title: Vero Beach Real Estate Podcast with Kathleen Provancher
  categories: Education
  image: /img/podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the Vero Beach
    Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from Provancher Team - your professional
    Vero Beach Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in Vero Beach, home
    selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer
  author: Kathleen Provancher
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /uploads/kathleen-provancher-logo.webp
  logo_width_number: 46
  hero_text: Vero Beach Real Estate Blog
  hero_background_hex: '#999999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#71cbca'
  theme_color: '#000c2a'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: rgba(0, 0, 0, 0)
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: rgba(0, 0, 0, 0)
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: rgba(0, 0, 0, 0)
  secondary_button_text_color: '#ffffff'
